[package]
name = "pool_pow"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pool_pow"
path = "pool_pow.rs"

[dependencies]
noid_core = { path = "../rust-external-miner/noid_core" }
noid_poseidon2b = { path = "../rust-external-miner/noid_poseidon2b" }
rayon = "1.10"
hex = "0.4"

[[bin]]
name = "pool_cpu_native"
path = "pool_cpu_native.rs"